apiVersion: apps/v1
kind: Deployment
metadata:
  name: minesweeper-client-deployment
  labels:
    app: minesweeper-client
spec:
  selector:
    matchLabels:
      app: minesweeper-client
  template:
    metadata:
      labels:
        app: minesweeper-client
    spec:
      containers:
      - name: minesweeper-client-container
        image: gcr.io/admin-project-312303/minesweeper-client:1.0-SNAPSHOT
        ports:
        - containerPort: 9081
---
apiVersion: v1
kind: Service
metadata:
  name: minesweeper-client-service
spec:
  type: NodePort
  selector:
    app: minesweeper-client
  ports:
  - protocol: TCP
    port: 9081
    targetPort: 9081
    nodePort: 32000
