apiVersion: apps/v1
kind: Deployment
metadata:
  name: minesweeper-api-deployment
  labels:
    app: minesweeper-api
spec:
  selector:
    matchLabels:
      app: minesweeper-api
  template:
    metadata:
      labels:
        app: minesweeper-api
    spec:
      containers:
      - name: minesweeper-api-container
        image: gcr.io/admin-project-312303/minesweeper-api:1.1-SNAPSHOT
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: minesweeper-api-service
spec:
  type: NodePort
  selector:
    app: minesweeper-api
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 31000
